/*
A random number is generated by the program and if user gets 3 tries if he guesses the number right thn he can play it again
and if he is not able to guess , the number shall be displayed in the end and cn choose if he wants to play further or not.
 */

import java.util.Scanner;// For taking input from user
//import java.lang.String;//

public class Mini_Project {
    public static void game() {//Game function
        int a = (int) (Math.random() * 10);//generating the random number
        for (int i = 1; i < 4; i++) { // starting the guessing of the number by user
            System.out.println("Enter the number");
            Scanner num = new Scanner(System.in);
            int number = num.nextInt();//user enters the number
            if (number == a) {  // correct guess
                System.out.println("Great you have correctly guessed the number 🤩 ");
                break;
            } else {// incorrect guess
                System.out.println("Oh 😔 you have guessed the wrong number \n Try again ");
            }
        }
            System.out.println("The number is " + a);// the number is declared at the end whether the user has inputted the number correct or not
    }

    public static void main(String args[]) {

        System.out.println("Lets start the game 😊. \n Enter the game you have to guess the number. \n You will get three tries and then the number shall be displayed you can later retry it.");
        game();//Calling game function for starting the game
        System.out.println("Do you want to play the game again ?");
        Scanner choice = new Scanner(System.in);// A string named choice is made to take the choice of user
        String wish = choice.nextLine();// The user is given choice if he/she wants to play the game
        if (wish.equals("Yes") || wish.equals("Y")) {// Game function is called since the user wants to pay the game again
            game();
        } else {
            System.exit(0);// The user has quit the game
        }
    }
}


